### ISSUE TITLE
Print command does not work

### ISSUE THREAD

**Issue by MathiasCiarlo** [larstvei/at#2]
Tried this command at UiO: `@ HOST print -P PRINTERNAME @myDocument`
The command only gives partial feedback from the printer: 

> Queued job at PRINTER

 or similar, but lacks information about how many sheets it queued. After checking the printer queue, it shows the job did not get queued.

**Comment by larstvei** [comment]
Hi!

This sounds like a problem with `print`. If you run a minimal command like `@ HOST ls`, do you get a reasonable output (e.i. equivalent with `ssh HOST ls`)? If `@` works like expected for simple commands (for instance the ones provided in the README), then there is really no reason for it to not work with `print` specifically.

Is the problem reproducible? If so, can you provide a series of steps that reproduces the error, along with the versions of `python` and `paramiko`?

I can note that I have been using `@` with `print` for months without having problems.

**Comment by MathiasCiarlo** [comment]
`@ HOST print -P PRINTER @DOCUMENT` produces the output:
Cannot open display "default display"
Queued on printer PRINTER:
  PDF file @-16cb673c-048e-11e6-8429-7c7a911c589a/DOCUMENT.

Normally the output would be (logged in):
`print -P PRINTER DOCUMENT`
Queued 1 sheet on printer PRINTER:
  PDF file DOCUMENT.
You are first in the queue to PRINTER.

Versions:
Python 2.7.10
Paramiko 1.16.0

**Comment by larstvei** [comment]
Ok, I'll look into it tomorrow.

**Comment by MathiasCiarlo** [comment]
Hi, this error reappeared! I think the problem might be the tilde! ~~~

$ @ host print -P printerName -ss @~/Desktop/tmp.cpp
Traceback (most recent call last):
  File "/home/user/apps/at/@.py", line 96, in <module>
    cmd, cleanup = sendfiles(argv[2:])
  File "/home/user/apps/at/@.py", line 71, in sendfiles
    sftp.put(f[1], r[1])
  File "/usr/local/lib/python2.7/dist-packages/paramiko/sftp_client.py", line 668, in put
    file_size = os.stat(localpath).st_size
OSError: [Errno 2] No such file or directory: '~/Desktop/tmp.cpp'
